name: Build Sphinx docs

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Record scores]
    types:
      - completed

jobs:
  build-sphinx-docs:
    name: Build Sphinx docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ivcurves requirements
        run: pip3 install -r requirements.txt
      - name: Install Sphinx docs requirements
        working-directory: docs/sphinx
        run: |
          pip3 install -U sphinx
          pip3 install -r requirements.txt
      - name: Generate Sphinx docs test case images
        working-directory: docs/sphinx/source
        run: |
          mkdir -p _static
          mkdir -p _images
          mkdir -p _images/test_cases
          python3 ../../../precise.py --save-images _images/test_cases
      - name: Rebuild Sphinx docs html
        working-directory: docs/sphinx
        run: |
          make html
          git config user.name "GitHub"
          git config user.email "github@ivcurves"
          git add build # The build html files
          git commit -m 'Update Sphinx docs'
          git push https://github.com/reepoi/ivcurves.git gh-pages # Make sure gh-pages branch exists in repo

