name: Update scores

on:
  workflow_dispatch:

jobs:
  get-pr-numbers:
    name: Get pull request numbers from scores database
    runs-on: ubuntu-latest
    outputs:
      pr-numbers: ${{ steps.matrix.outputs.pr-numbers }}
    steps:
      - name: Checkout pull request target
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Load scores database and get pull request numbers
        env:
          DATABASE_PATH: docs/sphinx/source/scores_database.json
        run: |
          export $PR_NUMBERS=''
          python3 -c "
          import json
          with open('${{ env.DATABASE_PATH }}', 'r') as file:
              database = json.load(file)
              print(list(database.keys()))
          " >> $PR_NUMBERS
          echo 'PR_NUMBERS=$PR_NUMBERS' >> ${{ github.env }}
      - name: Set pull request numbers output
        id: matrix
        run: |
          echo '::set-output name=pr-numbers::${{ env.PR_NUMBERS }}'
  build:
    needs: [ get-pr-numbers ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pr-number: ${{ fromJson(needs.get-pr-numbers.outputs.pr-numbers) }}
    steps:
      - run: |
          echo "${{ matrix.pr-number }}"

