
name: Update scores

on:
  workflow_dispatch:

jobs:
  get-pr-data:
    name: Get pull request data from scores database
    runs-on: ubuntu-latest
    outputs:
      pr-data: ${{ steps.matrix.outputs.pr-data }}
    steps:
      - name: Checkout pull request target
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Load scores database and get pull request data
        env:
          DATABASE_PATH: docs/sphinx/source/scores_database.json
        run: |
          export PR_DATA=$(python3 -c "
          import json
          with open('${{ env.DATABASE_PATH }}', 'r') as file:
              database = json.load(file)
          pr_data = []
          for pr_number, data in database.items():
              pair = {'pr_number': pr_number, 'username': data['username']}
              pr_data .append(pair)
          print(pr_data)
          ")
          echo PR_DATA=$PR_DATA >> ${{ github.env }}
      - name: Set pull request data output
        id: matrix
        run: |
          echo "::set-output name=pr-data::${{ env.PR_DATA }}"
  build:
    needs: get-pr-data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pr-data: ${{ fromJson(needs.get-pr-data.outputs.pr-data) }}
    steps:
      - run: |
          echo "${{ matrix.pr-data }}"
